// apps/angular-demo/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'JsHeroes Angular-Demo';

  currency = 'usd';
  currencyValue = '999.80';

  /**
    Normally, the two-way binding wouldn't work without using the Angular Output Wrapper from Stencil.
    Meaning that to update the variable in the controller, we should do it manually, something like e.g:

    <jsh-currency-field currency="usd" [value]="currencyValue" (jshChange)="onChangeValue($event)"></jsh-currency-field>

    onChangeValue(ev: Event) {
      const { value } = (ev as CustomEvent).detail as { value: string };
      this.currencyValue = value;
    }
  */

  onChangeValue() {
    console.log('Value changed', this.currencyValue);
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<jsh-welcome day-start="18" day-end="19th" month="May" year="2023" city="Cluj-Napoca, Romania"></jsh-welcome>
<div class="header">
  <h1>Welcome to {{ title }}!</h1>
  <img
    width="300"
    alt="Angular Logo"
    src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
  />
</div>
<div class="currency-field">
  <jsh-currency-field [currency]="currency" [(ngModel)]="currencyValue" (jshChange)="onChangeValue()"></jsh-currency-field>
</div>

// apps/react-demo/src/app/app.tsx
import { useState } from 'react';
import { JshCurrencyField, JshWelcome } from '@jsheroes/react';

import styles from './app.module.scss';

export function App() {
  const [currencyValue, setCurrencyState] = useState('100.99');

  const handleChange = (ev: CustomEvent<{ value: string }>) => {
    console.log('Currency value changed!', ev.detail.value);
    setCurrencyState(ev.detail.value);
  };

  return (
    <>
      <JshWelcome dayStart="18" dayEnd="19th" month="May" year="2023" city="Cluj-Napoca, Romania" />
      <div className={styles.header}>
        <h1 className={styles.h1}>
          <span> Hello there, </span>
          welcome to JsHeroes React-Demo 👋
        </h1>
        <img
          width="300"
          alt="Angular Logo"
          src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9Ii0xMS41IC0xMC4yMzE3NCAyMyAyMC40NjM0OCI+CiAgPHRpdGxlPlJlYWN0IExvZ288L3RpdGxlPgogIDxjaXJjbGUgY3g9IjAiIGN5PSIwIiByPSIyLjA1IiBmaWxsPSIjNjFkYWZiIi8+CiAgPGcgc3Ryb2tlPSIjNjFkYWZiIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIi8+CiAgICA8ZWxsaXBzZSByeD0iMTEiIHJ5PSI0LjIiIHRyYW5zZm9ybT0icm90YXRlKDYwKSIvPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIiB0cmFuc2Zvcm09InJvdGF0ZSgxMjApIi8+CiAgPC9nPgo8L3N2Zz4K"
        />
      </div>
      <div className={styles.currencyField}>
        <JshCurrencyField currency="eur" value={currencyValue} onJshChange={handleChange} />
      </div>
    </>
  );
}

export default App;

/* -------------------------------------------------------------------------- */
/*                                    Notes                                   */
/* -------------------------------------------------------------------------- */

/**
  When not using the React Output target from Stencil, you won't be able to bind to the component properties
  (e.g. <jsh-welcome dayStart={18}) and you can only use the component HTML attributes.

  ```
    <jsh-welcome day-start="18" day-end="19th" ... />
  ```

  Event binding will not work, and as a consumer, you need to make a reference to the component and attach an Event listener to the event.

  ```
    <jsh-currency-field currency="eur" value={currencyValue} ref={currencyField} />
  ```

  ```
    const currencyField = useRef<HTMLElement>(null);

    useEffect(() => {
      const customElem = currencyField.current;
      if (!customElem) return;

      const handleFieldChange = (ev: Event) => {
        const { value } = (ev as CustomEvent).detail as { value: string };
        setCurrencyState(value);
      };

      customElem.addEventListener('jshChange', handleFieldChange);
      return () => {
        customElem.removeEventListener('jshChange', handleFieldChange);
      };
    }, [])
  ```
*/
